### ISSUE TITLE
Merge upstream in gtksourceview

### ISSUE THREAD

**Issue by pbor** [rust-lang/gedit-config#4]
I would like to merge the rust.lang file uptream in gtksourceview (I am one of the maintainers) so that it is included by default in all the distros.

To go upstream I just need a confirmation that it is ok to relicense to LGPL2 as the rest of gtksourceview

**Comment by bkoropoff** [comment]
@alexcrichton, what's the licensing status of this repo?

**Comment by alexcrichton** [comment]
@pbor just to confirm, this _must_ be relicensed as LGPL2 for inclusion? We generally try to use the same license wherever possible.

@bkoropoff by default I believe it's under the normal Rust MIT/Apache2 license because it was forked off the main repo where all contributions were made. I believe changing the license here would involve getting consent from all previous contributors to the file for the relicensing.

cc @brson (more familiar with licensing than I)

**Comment by pbor** [comment]
@alexcrichton gtksourceview itself is all lgpl2 so it would surely make our life easier... I personally would not mind including a file licensed with a less restrictive license, but I fear that some distribution packagers would get picky and would have to state the mixed licenses in the metadata etc.

IANAL, but it should be possibile to simply relicense MIT code to lgpl2 as long as the original notice is preserved, no?

If we could ask a few contributors to relicense even better... it would just need to be the ones who made substantial contributions not all people who sent one liners like adding a missing keyword

**Comment by brson** [comment]
There's an issue open about this repo not declaring a license properly: https://github.com/rust-lang/rust/issues/25664

And here's a PR to fix the licensing of this repo: https://github.com/rust-lang/gedit-config/pull/5

@pbor My understanding is you are free to relicense the code from MIT to LGPL2. I am not certain the mechanics of doing this but would guess if you leave the copyright statement on the source file and then additionally add LGPL2 it is fine.

I do not know whether ASL2 code can be relicensed to LGPL2 (it can't be relicensed to GPL2), but that doesn't matter because you are free to only use the MIT license. Whether the ASL2 copyright statement should be left on any borrowed code I do not know.

cc @aturon More legal issues.

**Comment by pbor** [comment]
Since the freeze for the next release of gnome modules is imminent, I went ahead and committed the file upstream, relicensing to LGPL but keeping the old license notice.

https://git.gnome.org/browse/gtksourceview/commit/?id=ed2e100399f2dc974db1522abb1da1e5fbf74340

I hope it is ok. If there are any problems let me know.

It may also be worth adding a note to this project readme that the file is now upstream.

If in the future you have any bugreport/fix/improvement for the lang file, either file a report to bugzilla.gnome.org or contact me directly if you do not want to create an account there.
